### PR TITLE
feat(647): make a silent capture lane loud, per role, in /health

### LINKED ISSUE #647: Automatic-capture liveness check: prove the raw capture lane delivered for recent sessions, loud on silence (replaces the retired capture merge-gate)
Ledger item 25 (docs/issue-graph.md): the capture merge-gate tier is retired — raw capture is automatic (Stop hooks → watermark → durable spool) and distillation is the DREAM pipeline's designed job (docs/dream-design.md). The enforcement that replaces it is LIVENESS on the automatic lane, the #625 pattern: a wedged or silently-dead capture pipeline must be loudly distinguishable from a healthy one.

Shape (delta on existing designs, not an invention): a deterministic check that recent sessions' capture events actually reached the server (or are sitting in the spool with the outage latch announced) — asserting on event counts/watermark advancement, NEVER wall-clock assertions (lane-contract round 5). Loud on: watermark not advancing while sessions run; spool accumulating with no outage latch; zero capture events across N recent active sessions. Control clause required: healthy path stays healthy (#624 clause-z / round-8 rule). Related: #646 (provider scope contradiction), #451 (hydration stamp + recall telemetry remain), #625 (the pattern's precedent).

### PR DESCRIPTION
**Pull request by rodaddy**
## Summary

- Closes #647 (ledger item 25). The capture merge-gate was retired because gating a human's PR is the wrong instrument for a background pipeline. This is the replacement: **liveness on the automatic lane**, the #625 pattern applied to the second background lane.
- **This is not a new design — it is an existing one made executable.** `docs/decisions/capture-never-drops-a-turn.md` has specified the correct capture health check since 2026-07-28 (`:182-200`) and records at `:280` that "the check it asks for was never run". This PR runs it.
- New `openbrain.apps.capture.liveness`: a **pure function over counts**. It opens no file, holds no lock, and takes no clock of its own. That shape is deliberate — `outage.py`'s module docstring records what happened the last time a capture-path component held a lock another waited on: a **healthy** hook stalled 31.4s, past the 5s Stop deadline, and the turn delivered zero batches ("the turn was DROPPED by its own telemetry"). A liveness reader that could do that would be strictly worse than the blindness it removes.
- Three faults, all count-derived: watermark advancing **zero bytes while sessions run**; spool **accumulating with no outage announced** (`OutageLatch.note_spooled` returns `None` for three distinct reasons, so a latch that never fires is indistinguishable from a healthy one at the call site — `outage.py:411`); and any **role** delivering nothing.
- **Per role is load-bearing, not decoration.** `capture-never-drops-a-turn.md:188-200` specifies it and explains why with a measurement: the operator's numbers stayed healthy for six days while the assistant side sat at zero (#447). On 2026-08-02 that was 365 user rows against 13 assistant rows — a lane-total counter reads 365 turns and reports busy traffic. Summing across roles rebuilds the exact blind spot this exists to remove.
- `server/transport/health.ts` composes it exactly as `producerHealth` is composed (health.ts:129-134), **including the absence rule**: a process composing no capture lane publishes no block and stays green. Absent means "not my job"; `stale: true` means "my job and I am not doing it".
- **No wall-clock assertion anywhere.** `silence_seconds` is reported and never compared (lane-contract Tightenings round 5).

## Verification

- Done-means: scripts/done-means/647-capture-liveness.sh
- [x] Relevant Open Brain tests/typecheck/migrations passed
- [x] Python package checks passed or are not applicable
- [x] Live Open Brain smoke passed or is not applicable

**RED (before, commit `ec5948d`):** 10 of 13 clauses failed. Clause (d) reproduced the defect verbatim — `/health with a silent capture lane reported status=healthy, names-capture=false`. The two controls that *should* pass pre-fix (`f-health` absence, `g` injected-clock) already did, which is what distinguishes a discriminating check from one that fails everywhere.

**GREEN (after, commit `be0f6b2`):** 13/13.

```
PASS  (a) 12 sessions delivering, 0 bytes advanced -> stale=True watermark_wedged=True
PASS  (b) spool depth 137 with 0 announcements -> stale=True spool_unannounced=True
PASS  (b-announced) an ANNOUNCED outage of the same depth is not the silent-spool fault
PASS  (c) 9 active sessions, 0 turns delivered -> stale=True sessions_observed=9
PASS  (c-single) one quiet session alone does not declare the lane dead -> stale=False
PASS  (c-role) 365 user turns beside 0 assistant turns is a dead speaker, not a busy lane
PASS  (e) control: 9 sessions, 238 turns, 1MiB advanced, spool 0 -> stale=False
PASS  (f) an uncomposed capture lane yields None
PASS  (g) simulated 1800s of capture silence in 0.078s of wall clock
PASS  (d) /health with a silent capture lane reported status=degraded, names-capture=true
PASS  (e-health) control: healthy capture reading -> status=healthy, block published=true
PASS  (f-health) control: no capture lane composed -> status=healthy, capture block absent=true
PASS  (f-health-undefined) control: reader present but returns undefined -> status=healthy
```

**Suites:** `bun run test:isolated` → 3718 pass, 35 skip, **0 fail** (242 files, db `ob_isolated_25880_mskpqaya51`, dropped). `bunx tsc --noEmit` clean. `uv run mypy src/openbrain` → 50 files clean. `uv run ruff check src tests` → all checks passed. `uv run pytest -q` → 612 passed, 19 deselected — **identical to the same tree with the change stashed**, so nothing was silenced (round-10 skip-count rule).

**Mutation-tested (round-9 rule: a green clause is not evidence until seen to fail).** Five mutations, each caught by *its own* clause rather than by blanket failure:

| Mutation | Caught by |
|---|---|
| `stale=True` always | (e) control, (c-single) |
| sum across roles instead of per-role (rebuilds #447) | (c-role) *only* |
| absence returns a fabricated healthy reading | (f) *only* |
| absent lane degrades the worker (round-8 violation) | (f-health) |
| capture block published but excluded from status | (d) *only* |

**CI on the merged head (`8f11099`) — two red checks, both inherited, neither absorbed silently:**

- `db-integration` **fail**: `0 fail / 1 error`, `TypeError: proc.kill is not a function` at `src/tools/search-all.ts:110`. The known flake, already filed **twice** as #608 and #632. Evidence it is a race and not this PR: on head `be0f6b2` two runs of the SAME SHA disagreed (`check` passed in run 31272342608, failed in run 31272430693); on `8f11099` `check` passes twice while `db-integration` fails with the identical signature. It follows whichever job loses the race. Recurrence recorded on #632 rather than absorbed or re-run until green. This PR touches no subprocess code and does not modify `search-all.ts`.
- `GitGuardian` **fail**: scanning content merged in from #645, not from this branch. `git diff origin/main...HEAD` over the seven files this PR authors yields **zero** credential-shaped matches. This is the expected-noise class recorded in lane-contract Tightenings round 10.

**Merge note:** `main` advanced (#645) after the first push. The only conflict was `docs/sme/gotcha-agent.md`, which is a **generated** lane index — resolved by re-running `scripts/build-sme-indexes.ts`, never by hand, since the next build would silently overwrite a hand-resolution. No `order` collision (#645 took 66, this branch 67); rebuilt index carries 45 entries with both present. Post-merge re-verification: done-means 13/13, `tsc` clean, `test:isolated` 3718 pass / 0 fail, mypy + ruff clean, pytest 611 passed / 1 skipped — that skip (`test_receipts_scope.py:176`, "the temp workspace volume is not mounted") arrived with #645 and reproduces on the tree without this branch's changes.

## Critical Self-Review

- Highest-risk behavior: a false-positive `stale` degrading `/health` on a healthy worker, since `/health` gates load balancing on core01's two workers. Mitigated structurally: absence and `undefined` both stay green (clauses f, f-health, f-health-undefined), and `MIN_SESSIONS_FOR_SILENCE = 2` keeps a single quiet session from tripping it (clause c-single). **No caller composes `captureHealth` in this PR**, so live blast radius is currently zero.
- Assumptions that could be wrong: (1) that `sessions_observed` is a trustworthy denominator — the counter's *gatherer* is not built here, so a miscounting gatherer could manufacture either a false stale or a false green; (2) that role keys match `ob_raw_turns.role` values — asserted from the SQL at `capture-never-drops-a-turn.md:193-197`, not enforced by a shared enum; (3) that `MIN_SESSIONS_FOR_SILENCE = 2` is the right floor — chosen against the #447 evidence (a lane at literal zero for a full day), not tuned against a false-positive corpus.
- Missing/weak tests: the reader has a done-means check and doctests but **no unit-test file** — deliberate, since the done-means driver exercises every branch through the shipped function and a second copy would drift. The gap that matters: **nothing tests the gatherer, because there is no gatherer** (see residual risk).
- Security/permission risk: none identified. No namespace predicate, no ID-based read, no SQL, no auth surface. The reading is content-free by construction — counts, boolean flags, and role names only; `reason` carries no transcript text, path, or endpoint, matching the rule `outage.py`'s notices already follow.
- Migration/deploy risk: none. No schema change, no migration. `captureHealth` is an optional input; every existing caller compiles and behaves identically (`tsc` clean, 3718 tests unchanged).
- Downstream client/runtime risk: `SingleWorkerHealth` gains one **optional** field. Additive to a response body, so existing consumers are unaffected; `docs/downstream-rollout.md` classifies below — the block is absent on every process today.
- Rollback/cleanup concern: revert is a clean two-file revert plus deleting one new module. No state is written, so nothing needs undoing.
- Fixes made before PR: (1) **self-caught false-GREEN defect in my own driver** — an exception escaping `main()` left the TS driver exiting **0**, so a crashing subject would have banked a pass. Found while mutation-testing, not in any green run; fixed with an explicit `.catch` → `exit(1)` and **re-proven under the same mutation** (round-8: a repaired clause has never failed in its current form). (2) Removed an unused `Sequence` import ruff flagged.
- Known residual risk: **the reading is WRITTEN, not RUNNING.** This PR builds the reader and the health composition; **no process composes `captureHealth` yet**, so no live `/health` reports capture today. That is deliberate scope — the gatherer must decide where per-session counts are aggregated across a fleet whose watermark and latch stores expose **no enumeration method** (`WatermarkStore` and `OutageLatch` are strictly single-key; confirmed by reading both). Designing that enumeration is a real decision, not a detail, and it belongs to its own lane rather than being invented silently here. Flagged for the decisions pass; the check proves the mechanism, not a live deployment.
- SME review-memory update: [x] `docs/sme/` updated or [ ] not applicable because:

## Review Gate

- [x] Critical self-review fields above are filled with specific, non-placeholder content
- [x] MEDIUM+ review findings were captured in `docs/sme/` or explicitly marked not applicable
- Live Open Brain checks: [ ] linked below or [x] not applicable because: nothing composes the reader yet, so there is no live surface to smoke. The reading is WRITTEN, not RUNNING, and the PR says so rather than implying deployment.

## Contract Parity

- Contract parity: [ ] fixtures updated
- Contract parity: [x] runtime-specific because: the `capture` block is an optional, additive field on the TypeScript `/health` response, absent on every process today. No contract fixture asserts its presence, and the Python side of this PR is a pure local reader that crosses no wire.

## Downstream Rollout

- [x] I checked `docs/downstream-rollout.md`
- [x] rtech-mcps handoff is complete or not applicable
- [x] mcp2cli cache/skill refresh is complete or not applicable
- [x] rtech-hermes Python runtime/plugin changes are complete or not applicable
- [x] Hermes live rollout/canaries are complete or not applicable

Notes/evidence:

- Not applicable across every downstream row, for one reason: **no MCP tool, schema, or protocol surface changed.** `/health` gains one optional response field that is absent on all current processes, and no MCP tool signature, transport contract, or Python client wrapper was touched. Nothing downstream can observe this PR until a follow-up composes the reader — at which point the rollout classification is worth re-running against a surface that actually exists.

### CODE REVIEW

**Comment by rodaddy** [comment]
verify-lane receipt: check=scripts/done-means/647-capture-liveness.sh exit=0 sha=8f1109933750d60680ad354ddc5ad471fcbd0f58 at=2026-08-08T18:58:34.187Z

<details><summary>check output (tail)</summary>

```
INFO  repo:   /Users/rico/.cache/open-brain/_worktrees/verify-lane-pr-648-41636mskqldcn
INFO  drivers: scripts/done-means/647_capture_liveness_driver.py (capture-side liveness, injected clock)
INFO           scripts/done-means/647-capture-liveness.driver.ts (health composition, injected reading)

--- capture-side clauses (a) (b) (c) (e) (f) (g) ---
PASS  (a) 12 sessions delivering, 0 bytes advanced -> stale=True watermark_wedged=True reason='watermark advanced 0 bytes across 12 session(s); role(s) delivered nothing: assistant, user'
PASS  (b) spool depth 137 with 0 announcements -> stale=True spool_unannounced=True reason='spool holds 137 record(s) with no outage announced'
PASS  (b-announced) an ANNOUNCED outage of the same depth is not the silent-spool fault -> spool_unannounced=False
PASS  (c) 9 active sessions, 0 turns delivered -> stale=True sessions_observed=9 reason='watermark advanced 0 bytes across 9 session(s); role(s) delivered nothing: assistant, user'
PASS  (c-single) one quiet session alone does not declare the lane dead -> stale=False
PASS  (c-role) 365 user turns beside 0 assistant turns is a dead speaker, not a busy lane -> stale=True silent_roles=('assistant',) reason='role(s) delivered nothing: assistant'
PASS  (e) control: 9 sessions, 238 turns across both roles, 1MiB advanced, spool 0 -> stale=False wedged=False spool_unannounced=False silent_roles=()
PASS  (f) an uncomposed capture lane yields None (expected None: absent means 'not my job', not 'broken', and not 'fine')
PASS  (g) simulated 1800s of capture silence in 0.347s of wall clock -- clock is injected, not slept

clauses: 9 run, 0 failed

--- health-composition clauses (d) (e-health) (f-health) ---
PASS  (d) /health with a silent capture lane reported status=degraded, names-capture=true, warn-line=true
PASS  (e-health) control: healthy capture reading -> status=healthy, block published=true
PASS  (f-health) control: no capture lane composed -> status=healthy, capture block absent=true
PASS  (f-health-undefined) control: reader present but returns undefined -> status=healthy

clauses: 4 run, 0 failed

DONE-MEANS #647: PASS — a silent capture lane is loudly stale and turns /health non-green; a healthy lane stays green and an absent one is not reported broken.
Using CPython 3.13.14
Creating virtual environment at: /Users/rico/.cache/open-brain/_worktrees/verify-lane-pr-648-41636mskqldcn/python/.venv
   Building openbrain @ file:///Users/rico/.cache/open-brain/_worktrees/verify-lane-pr-648-41636mskqldcn/python/openbrain
   Building openbrain-memory @ file:///Users/rico/.cache/open-brain/_worktrees/verify-lane-pr-648-41636mskqldcn/python/openbrain-memory
      Built openbrain @ file:///Users/rico/.cache/open-brain/_worktrees/verify-lane-pr-648-41636mskqldcn/python/openbrain
      Built openbrain-memory @ file:///Users/rico/.cache/open-brain/_worktrees/verify-lane-pr-648-41636mskqldcn/python/openbrain-memory
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 44 packages in 1.34s
```

</details>

Posted by `scripts/verify-lane.ts`. The SHA above is the PR head observed at run time;
`.claude/hooks/merge-gate.ts` refuses the merge if the PR has moved since.

**Comment by rodaddy** [comment]
harvested: 3911ace — round-13 Tightenings on wip/2026-08-07.
